'use server';

import { revalidatePath } from 'next/cache';
import { redirect }       from 'next/navigation';
import { createClient }   from '@/lib/supabase/server';
import { getLocale }      from 'next-intl/server';
import { writeAuditLog }  from '@/lib/audit';

// ── Types ─────────────────────────────────────────────────────────

export interface GenerateInviteResult {
  url:        string;
  token:      string;
  expires_at: string;
}

export interface AcceptInviteResult {
  case_id: string;
}

// ── generateInvite ────────────────────────────────────────────────
/**
 * Creates a new invite token for the given case.
 * Only the client_owner of the case may call this.
 * Revokes any existing pending invite for the same case first.
 * Returns the full invite URL.
 */
export async function generateInvite(
  caseId: string,
  invitedEmail?: string
): Promise<GenerateInviteResult> {
  const supabase = await createClient();
  const locale   = await getLocale();

  const { data: { user } } = await supabase.auth.getUser();
  if (!user) throw new Error('Not authenticated');

  // RLS check: user must own the case
  const { data: c } = await supabase
    .from('cases')
    .select('id, title')
    .eq('id', caseId)
    .eq('client_id', user.id)
    .maybeSingle();

  if (!c) throw new Error('Case not found or access denied');

  // Revoke all existing pending invites for this case
  await supabase
    .from('invites')
    .update({ revoked_at: new Date().toISOString() })
    .eq('case_id', caseId)
    .eq('created_by', user.id)
    .is('accepted_at', null)
    .is('revoked_at', null);

  // Create new invite row — token is a UUID, generated by Postgres default
  const { data: invite, error } = await supabase
    .from('invites')
    .insert({
      case_id:       caseId,
      created_by:    user.id,
      invited_email: invitedEmail ?? null,
    })
    .select('id, token, expires_at')
    .single();

  if (error || !invite) {
    throw new Error(error?.message ?? 'Failed to create invite');
  }

  await writeAuditLog({
    user_id:   user.id,
    action:    'lawyer_invite',
    resource:  'invites',
    resource_id: invite.id,
    severity:  'info',
    metadata:  { case_id: caseId, invited_email: invitedEmail },
  });

  // Build invite URL: /[locale]/invite?token=[uuid]
  const appUrl = process.env.NEXT_PUBLIC_APP_URL ?? 'https://wakeelai-sigma.vercel.app';
  const inviteUrl = `${appUrl}/${locale}/invite?token=${invite.token}`;

  revalidatePath(`/${locale}/cases/${caseId}`);

  return {
    url:        inviteUrl,
    token:      invite.token,
    expires_at: invite.expires_at,
  };
}

// ── acceptInvite ──────────────────────────────────────────────────
/**
 * Accepts a lawyer invite by token.
 * Validates: exists, not expired, not already accepted, not self-invite.
 * Idempotent: if lawyer already in case_lawyers → skips insert.
 * On success: updates case_lawyers, marks invite accepted, logs timeline,
 *             redirects to lawyer portal.
 */
export async function acceptInvite(token: string): Promise<never> {
  const supabase = await createClient();
  const locale   = await getLocale();

  const { data: { user } } = await supabase.auth.getUser();
  if (!user) {
    const returnTo = encodeURIComponent(`/${locale}/invite?token=${token}`);
    redirect(`/${locale}/login?redirectTo=${returnTo}`);
  }

  // Validate token
  const { data: invite } = await supabase
    .from('invites')
    .select('id, case_id, created_by, expires_at, accepted_at, revoked_at')
    .eq('token', token)
    .maybeSingle();

  if (!invite) {
    redirect(`/${locale}/invite?token=${token}&error=invalid`);
  }
  if (invite.revoked_at) {
    redirect(`/${locale}/invite?token=${token}&error=revoked`);
  }
  if (invite.accepted_at) {
    redirect(`/${locale}/invite?token=${token}&error=used`);
  }
  if (new Date(invite.expires_at) < new Date()) {
    redirect(`/${locale}/invite?token=${token}&error=expired`);
  }
  if (invite.created_by === user.id) {
    redirect(`/${locale}/invite?token=${token}&error=self`);
  }

  // Idempotency: check if lawyer already in case_lawyers
  const { data: existing } = await supabase
    .from('case_lawyers')
    .select('id, status')
    .eq('case_id', invite.case_id)
    .eq('lawyer_id', user.id)
    .maybeSingle();

  if (existing?.status === 'active') {
    // Already accepted — skip directly to lawyer portal
    redirect(`/${locale}/lawyer/cases/${invite.case_id}`);
  }

  // Get lawyer profile for audit
  const { data: profile } = await supabase
    .from('users')
    .select('role, bar_number, jurisdiction')
    .eq('id', user.id)
    .maybeSingle();

  // Upgrade role to lawyer if currently client
  if (profile?.role === 'client') {
    await supabase.from('users')
      .update({ role: 'lawyer' })
      .eq('id', user.id);
  }

  // Insert / reactivate case_lawyers row with read_write permissions
  await supabase.from('case_lawyers').upsert(
    {
      case_id:     invite.case_id,
      lawyer_id:   user.id,
      invited_by:  invite.created_by,
      status:      'active',
      permissions: 'read_write',
    },
    { onConflict: 'case_id,lawyer_id' }
  );

  // Mark invite accepted
  await supabase
    .from('invites')
    .update({
      accepted_at: new Date().toISOString(),
      accepted_by: user.id,
    })
    .eq('id', invite.id);

  // Also mark the lawyer_invites table if token exists there (backward compat)
  await supabase
    .from('lawyer_invites')
    .update({ status: 'accepted', accepted_by: user.id, accepted_at: new Date().toISOString() })
    .eq('case_id', invite.case_id)
    .eq('status', 'pending');

  // Append to timeline
  await supabase.from('timeline_events').insert({
    case_id:             invite.case_id,
    actor_id:            user.id,
    event_type:          'lawyer_joined',
    payload: {
      lawyer_id:    user.id,
      bar_number:   profile?.bar_number   ?? null,
      jurisdiction: profile?.jurisdiction ?? null,
      via:          'invite_token',
    },
    is_system_generated: true,
  });

  // Notify the case owner
  try {
    await supabase.from('notifications').insert({
      user_id:    invite.created_by,
      type:       'lawyer_joined',
      title:      'Lawyer joined your case',
      body:       'A lawyer has accepted your invite and joined the case.',
      action_url: `/cases/${invite.case_id}`,
    });
  } catch { /* non-critical */ }

  await writeAuditLog({
    user_id:    user.id,
    action:     'lawyer_accept',
    resource:   'invites',
    resource_id: invite.id,
    severity:   'info',
    metadata:   { case_id: invite.case_id },
  });

  revalidatePath(`/cases/${invite.case_id}`);

  redirect(`/${locale}/lawyer/cases/${invite.case_id}`);
}
