import { NextResponse }       from 'next/server';
import { createClient }       from '@/lib/supabase/server';

// ──────────────────────────────────────────────────────────────────
// POST /api/vault/share
//
// Body: { document_id: string, expiry_hours?: number, max_accesses?: number }
//
// Creates a vault_shares row and returns the public share URL.
// The caller must own the document (enforced via RLS + explicit check).
//
// PRD Screen 6 — Evidence Vault time-limited share link
// Gap Analysis Task 4
// ──────────────────────────────────────────────────────────────────

export async function POST(req: Request) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

  let body: { document_id?: string; expiry_hours?: number; max_accesses?: number };
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: 'Invalid JSON' }, { status: 400 });
  }

  const { document_id, expiry_hours = 24, max_accesses = 5 } = body;

  if (!document_id) {
    return NextResponse.json({ error: 'document_id required' }, { status: 400 });
  }

  // Clamp inputs to sensible ranges
  const clampedHours   = Math.min(Math.max(Number(expiry_hours)  || 24, 1), 168); // 1 h – 7 days
  const clampedAccess  = Math.min(Math.max(Number(max_accesses)  || 5,  1), 100);

  // Verify the document belongs to a case owned by the current user
  const { data: doc, error: docErr } = await supabase
    .from('documents')
    .select('id, file_path, file_name, case_id')
    .eq('id', document_id)
    .maybeSingle();

  if (docErr || !doc) {
    return NextResponse.json({ error: 'Document not found' }, { status: 404 });
  }

  // Extra ownership check: the document's case must belong to this user
  const { data: caseRow } = await supabase
    .from('cases')
    .select('id')
    .eq('id', doc.case_id)
    .eq('client_id', user.id)
    .maybeSingle();

  if (!caseRow) {
    return NextResponse.json({ error: 'Forbidden' }, { status: 403 });
  }

  // Create the vault_shares row (token is generated by DB default)
  const expiresAt = new Date(Date.now() + clampedHours * 3_600_000).toISOString();

  const { data: share, error: shareErr } = await supabase
    .from('vault_shares')
    .insert({
      document_id,
      created_by:    user.id,
      expires_at:    expiresAt,
      max_accesses:  clampedAccess,
    })
    .select('token, expires_at, max_accesses')
    .single();

  if (shareErr || !share) {
    console.error('[VaultShare] insert error:', shareErr);
    return NextResponse.json({ error: 'Failed to create share link' }, { status: 500 });
  }

  const appUrl   = process.env.NEXT_PUBLIC_APP_URL ?? 'https://wakeela.com';
  const shareUrl = `${appUrl}/share/${share.token}`;

  return NextResponse.json({
    share_url:    shareUrl,
    token:        share.token,
    expires_at:   share.expires_at,
    max_accesses: share.max_accesses,
    file_name:    doc.file_name,
  }, { status: 201 });
}

// ──────────────────────────────────────────────────────────────────
// GET /api/vault/share?document_id=xxx
// Returns all active (non-expired) share links for a document.
// Only the document owner can call this.
// ──────────────────────────────────────────────────────────────────
export async function GET(req: Request) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

  const url        = new URL(req.url);
  const documentId = url.searchParams.get('document_id');
  if (!documentId) return NextResponse.json({ error: 'document_id required' }, { status: 400 });

  const { data: shares } = await supabase
    .from('vault_shares')
    .select('id, token, expires_at, accessed_count, max_accesses, created_at')
    .eq('document_id', documentId)
    .eq('created_by', user.id)
    .gte('expires_at', new Date().toISOString()) // only non-expired
    .order('created_at', { ascending: false });

  const appUrl = process.env.NEXT_PUBLIC_APP_URL ?? 'https://wakeela.com';

  return NextResponse.json(
    (shares ?? []).map((s) => ({
      ...s,
      share_url: `${appUrl}/share/${s.token}`,
    }))
  );
}
